config/routes.rb
Rails.application.routes.draw do
  # Admin
  get "admin" => "admin#index"
  get "admin/index" => "admin#index" # FIXME: remove this
  match "admin/edit_user", :via => [:post, :get]
  match "admin/reset_password", :via => [:post, :get]

  # Advertisements
  resources :advertisements do
    collection do
      post :update_multiple
    end
    member do
      get :redirect
    end
  end

  # Artist
  match "artist(.:format)" => "artist#index", :via => [:post, :get]
  match "artist/index(.:format)" => "artist#index", :via => [:post, :get] # FIXME: remove this
  match "artist/create(.:format)", :via => [:post, :get]
  match "artist/destroy(.:format)(/:id)" => "artist#destroy", :via => [:post, :get]
  match "artist/preview", :via => [:post, :get]
  match "artist/show(/:id)" => "artist#show", :via => [:post, :get]
  match "artist/update(.:format)(/:id)" => "artist#update", :via => [:post, :get]

  # Banned
  match "banned" => "banned#index", :via => [:post, :get]
  match "banned/index" => "banned#index", :via => [:post, :get] # FIXME: remove this

  # Batch
  match "batch" => "batch#index", :via => [:post, :get]
  match "batch/index" => "batch#index", :via => [:post, :get] # FIXME: remove this
  match "batch/create", :via => [:post, :get]
  post "batch/enqueue"
  post "batch/update"

  # Blocks
  post "blocks/block_ip"
  post "blocks/unblock_ip"

  # Comment
  match "comment" => "comment#index", :via => [:post, :get]
  match "comment/index" => "comment#index", :via => [:post, :get] # FIXME: remove this
  match "comment/edit(/:id)" => "comment#edit", :via => [:post, :get]
  match "comment/moderate", :via => [:post, :get]
  match "comment/search", :via => [:post, :get]
  match "comment/show(.:format)(/:id)" => "comment#show", :via => [:post, :get]
  match "comment/destroy(.:format)(/:id)" => "comment#destroy", :via => [:post, :delete]
  match "comment/update(/:id)" => "comment#update", :via => [:post, :put]
  post "comment/create(.:format)"
  post "comment/mark_as_spam(/:id)" => "comment#mark_as_spam"

  # Dmail
  match "dmail(/inbox)" => "dmail#inbox", :via => [:post, :get]
  match "dmail/compose", :via => [:post, :get]
  get "dmail/preview"
  match "dmail/show(/:id)" => "dmail#show", :via => [:post, :get]
  match "dmail/show_previous_messages", :via => [:post, :get]
  post "dmail/create"
  get "dmail/mark_all_read" => "dmail#confirm_mark_all_read"
  post "dmail/mark_all_read"

  # Favorite
  match "favorite/list_users(.:format)", :via => [:post, :get]

  # Forum
  match "forum(.:format)" => "forum#index", :via => [:post, :get]
  match "forum/index(.:format)" => "forum#index", :via => [:post, :get] # FIXME: remove this
  match "forum/preview", :via => [:post, :get]
  match "forum/new", :via => [:post, :get]
  match "forum/add", :via => [:post, :get]
  match "forum/edit(/:id)" => "forum#edit", :via => [:post, :get]
  match "forum/show(/:id)" => "forum#show", :via => [:post, :get]
  match "forum/search", :via => [:post, :get]
  match "forum/mark_all_read", :via => [:post, :get]
  match "forum/lock", :via => [:post, :put]
  match "forum/stick(/:id)" => "forum#stick", :via => [:post, :put]
  match "forum/unlock(/:id)" => "forum#unlock", :via => [:post, :put]
  match "forum/unstick(/:id)" => "forum#unstick", :via => [:post, :put]
  match "forum/update(/:id)" => "forum#update", :via => [:post, :put]
  match "forum/destroy(/:id)" => "forum#destroy", :via => [:post, :delete]
  post "forum/create"

  # Help
  get "help(/:page)" => "help#show", :as => "help"

  # History
  match "history" => "history#index", :via => [:post, :get]
  match "history/index" => "history#index", :via => [:post, :get] # FIXME: remove this
  post "history/undo"

  # Inline
  match "inline" => "inline#index", :via => [:post, :get]
  match "inline/index" => "inline#index", :via => [:post, :get] # FIXME: remove this
  match "inline/add_image(/:id)" => "inline#add_image", :via => [:post, :get]
  match "inline/create", :via => [:post, :get]
  match "inline/crop(/:id)" => "inline#crop", :via => [:post, :get]
  match "inline/edit(/:id)" => "inline#edit", :via => [:post, :get]
  match "inline/copy(/:id)" => "inline#copy", :via => [:post, :put]
  match "inline/update(/:id)" => "inline#update", :via => [:post, :put]
  match "inline/delete(/:id)" => "inline#delete", :via => [:post, :delete]
  match "inline/delete_image(/:id)" => "inline#delete_image", :via => [:post, :delete]

  # JobTask
  match "job_task" => "job_task#index", :via => [:post, :get]
  match "job_task/index" => "job_task#index", :via => [:post, :get] # FIXME: remove this
  match "job_task/destroy(/:id)" => "job_task#destroy", :via => [:post, :get]
  match "job_task/restart(/:id)" => "job_task#restart", :via => [:post, :get]
  match "job_task/show(/:id)" => "job_task#show", :via => [:post, :get]

  # Note
  match "note(.:format)" => "note#index", :via => [:post, :get]
  match "note/index(.:format)" => "note#index", :via => [:post, :get] # FIXME: remove this
  match "note/history(.:format)(/:id)" => "note#history", :via => [:post, :get]
  match "note/search(.:format)", :via => [:post, :get]
  match "note/revert(.:format)(/:id)" => "note#revert", :via => [:post, :put]
  match "note/update(.:format)(/:id)" => "note#update", :via => [:post, :put]

  # Pool
  match "pool(.:format)" => "pool#index", :via => [:post, :get]
  match "pool/index(.:format)" => "pool#index", :via => [:post, :get] # FIXME: remove this
  match "pool/add_post(.:format)" => "pool#add_post", :via => [:post, :get]
  match "pool/copy(/:id)" => "pool#copy", :via => [:post, :get]
  match "pool/create(.:format)" => "pool#create", :via => [:post, :get]
  match "pool/destroy(.:format)(/:id)" => "pool#destroy", :via => [:post, :get]
  match "pool/import(/:id)" => "pool#import", :via => [:post, :get]
  match "pool/order(/:id)" => "pool#order", :via => [:post, :get]
  match "pool/remove_post(.:format)" => "pool#remove_post", :via => [:post, :get]
  match "pool/select", :via => [:post, :get]
  match "pool/show(.:format)(/:id)" => "pool#show", :via => [:post, :get]
  match "pool/transfer_metadata", :via => [:post, :get]
  match "pool/update(.:format)(/:id)" => "pool#update", :via => [:post, :get]
  get "pool/zip/:id" => "pool#zip"

  # Post
  get "post(.:format)" => "post#index"
  get "post/index(.:format)" => "post#index" # FIXME: remove this
  match "post/acknowledge_new_deleted_posts", :via => [:post, :get]
  match "post/activate", :via => [:post, :get]
  get "post/atom(.:format)" => "post#atom", :defaults => { :format => :atom }
  match "post/browse", :via => [:post, :get]
  match "post/delete(/:id)" => "post#delete", :via => [:post, :get]
  match "post/deleted_index", :via => [:post, :get]
  get "post/error"
  match "post/moderate", :via => [:post, :get]
  get "post/piclens", :defaults => { :format => :rss }
  match "post/popular_by_day", :via => [:post, :get]
  match "post/popular_by_month", :via => [:post, :get]
  match "post/popular_by_week", :via => [:post, :get]
  match "post/popular_recent", :via => [:post, :get]
  match "post/random(/:id)" => "post#random", :via => [:post, :get]
  get "post/show(/:id)(/*tag_title)" => "post#show", :constraints => { :id => /\d+/ }, :format => false
  match "post/similar(/:id)" => "post#similar", :via => [:post, :get]
  match "post/undelete(/:id)" => "post#undelete", :via => [:post, :get]
  match "post/update_batch", :via => [:post, :get]
  match "post/upload", :via => [:post, :get]
  match "post/upload_problem", :via => [:post, :get]
  match "post/view(/:id)" => "post#view", :via => [:post, :get]
  match "post/flag(/:id)" => "post#flag", :via => [:post, :put]
  match "post/revert_tags(.:format)(/:id)" => "post#revert_tags", :via => [:post, :put]
  match "post/update(.:format)(/:id)" => "post#update", :via => [:post, :put]
  match "post/vote(.:format)(/:id)" => "post#vote", :via => [:post, :put]
  match "post/destroy(.:format)(/:id)" => "post#destroy", :via => [:post, :delete]
  post "post/create(.:format)" => "post#create"

  match "atom" => "post#atom", :defaults => { :format => :atom }, :via => [:post, :get]

  # Report
  match "report/tag_updates", :via => [:post, :get]
  match "report/note_updates", :via => [:post, :get]
  match "report/wiki_updates", :via => [:post, :get]
  match "report/post_uploads", :via => [:post, :get]
  match "report/votes", :via => [:post, :get]
  match "report/set_dates", :via => [:post, :get]

  # Settings
  namespace :settings do
    resource :api, :only => [:show, :update]
  end

  # Static
  match "static/500", :via => [:post, :get]
  match "static/more", :via => [:post, :get]
  match "static/terms_of_service", :via => [:post, :get]
  match "/opensearch" => "static#opensearch", :via => [:post, :get]

  # TagAlias
  match "tag_alias" => "tag_alias#index", :via => [:post, :get]
  match "tag_alias/index" => "tag_alias#index", :via => [:post, :get] # FIXME: remove this
  match "tag_alias/update", :via => [:post, :put]
  post "tag_alias/create"

  # Tag
  match "tag(.:format)" => "tag#index", :via => [:post, :get]
  match "tag/index(.:format)" => "tag#index", :via => [:post, :get] # FIXME: remove this
  get "tag/autocomplete_name", :as => :ac_tag_name
  match "tag/cloud", :via => [:post, :get]
  match "tag/edit(/:id)" => "tag#edit", :via => [:post, :get]
  match "tag/edit_preview", :via => [:post, :get]
  match "tag/mass_edit", :via => [:post, :get]
  match "tag/popular_by_day", :via => [:post, :get]
  match "tag/popular_by_month", :via => [:post, :get]
  match "tag/popular_by_week", :via => [:post, :get]
  match "tag/related(.:format)" => "tag#related", :via => [:post, :get]
  match "tag/show(/:id)" => "tag#show", :via => [:post, :get]
  get "tag/summary"
  post "tag/update(.:format)" => "tag#update"

  # TagImplication
  match "tag_implication" => "tag_implication#index", :via => [:post, :get]
  match "tag_implication/index" => "tag_implication#index", :via => [:post, :get] # FIXME: remove this
  match "tag_implication/update", :via => [:post, :put]

app/models/post.rb
class Post < ActiveRecord::Base
  STATUSES = %w(active pending flagged deleted)

  define_callbacks :delete
  define_callbacks :undelete
  has_many :notes, lambda { order "id DESC" }
  has_one :flag_detail, :class_name => "FlaggedPostDetail"
  belongs_to :user
  before_validation :set_random!, :on => :create
  before_create :set_index_timestamp!
  belongs_to :approver, :class_name => "User"
  attr_accessor :updater_ip_addr, :updater_user_id
  attr_accessor :metatag_flagged
  has_many :post_votes
  has_many :avatars, :class_name => "User", :foreign_key => "avatar_post_id"
  set_callback :delete, :before, :clear_avatars
  after_save :commit_flag
  has_and_belongs_to_many :_tags, :class_name => "Tag"
  scope :available, lambda { where.not :status => "deleted" }
  scope :has_any_tags, lambda { |tags| where("posts.tags_array && ARRAY[?]::varchar[]", Array(tags)) }
  scope :has_all_tags, lambda { |tags| where("posts.tags_array @> ARRAY[?]::varchar[]", Array(tags)) }
  scope :flagged, lambda { where "status = ?", "flagged" }

  def self.slow_has_all_tags(tags)
    p = Post.scoped
    t_ids = Tag.where(:name => tags).pluck(:id)
    t_ids.each do |t_id|
      p = p.where(:id => PostsTag.where(:tag_id => t_id).select(:post_id))
    end
    p
  end

  def self.slow_has_any_tags(tags)
    t_ids = Tag.where(:name => tags).pluck(:id)
    Post.where(:id => PostsTag.where(:tag_id => t_ids).select(:post_id))
  end

  def next_id
    Post.available.where("posts.id > ?", id).minimum(:id)
  end

  def previous_id
    Post.available.where("posts.id < ?", id).maximum(:id)
  end

  include Post::SqlMethods
  include Post::CommentMethods
  include Post::ImageStoreMethods
  include Post::VoteMethods
  include Post::TagMethods
  include Post::CountMethods
  include Post::CacheMethods
  include Post::ParentMethods
  include Post::FileMethods
  include Post::ChangeSequenceMethods
  include Post::RatingMethods
  include Post::StatusMethods
  include Post::ApiMethods
  include Post::MirrorMethods
  include Post::FrameMethods

  def destroy_with_reason(reason, current_user)
    transaction do
      flag!(reason, current_user.id)

      if flag_detail
        flag_detail.update(:is_resolved => true)
      end

      delete
    end
  end

  def self.destroy_with_reason(id, reason, current_user)
    post = Post.find(id)
    post.destroy_with_reason(reason, current_user)
  end

  def delete
    run_callbacks :delete do
      update(:status => "deleted")
    end
  end

  def undelete
    return if status == "active"
    run_callbacks :undelete do
      update(:status => "active")
    end
  end

  def can_user_delete?(user)
    return false unless user.has_permission?(self)

    return false if !user.is_mod_or_higher? && !is_held && created_at < 1.day.ago

    true
  end

  def clear_avatars
    User.clear_avatars(id)
  end

  def set_random!
    self.random = rand
  end

  def set_index_timestamp!
    self.index_timestamp = (self.created_at ||= Time.now)
  end

  def set_flag_detail(reason, creator_id)
    if flag_detail
      flag_detail.update(:reason => reason, :user_id => creator_id, :created_at => Time.now)
    else
      create_flag_detail!(:reason => reason, :user_id => creator_id, :is_resolved => false)
    end
  end

  def flag!(reason, creator_id)
    transaction do
      update(:status => "flagged")
      set_flag_detail(reason, creator_id)
    end
  end

  # If the flag_post metatag was used and the current user has access, flag the post.
  def commit_flag
    return if metatag_flagged.nil?
    return unless Thread.current["danbooru-user"].is_mod_or_higher?
    return if status != "active"

    self.flag!(metatag_flagged, Thread.current["danbooru-user"].id)
  end

  def approve!(approver_id)
    old_status = status

    if flag_detail
      flag_detail.update(:is_resolved => true)
    end

    update(:status => "active", :approver_id => approver_id)

    # Don't bump posts if the status wasn't "pending"; it might be "flagged".
    if old_status == "pending" && CONFIG["hide_pending_posts"]
      touch_index_timestamp
    end
    # Always try to save to trigger history logging.
    self.save!
  end

  def voted_by
    # FIXME: shouldn't include user_blacklist_tags at all (used by API return).
    @voted_by ||=
      User.select(:name, :id, "post_votes.score AS vote_score")
        .joins(:post_votes)
        .includes(:user_blacklisted_tags)
        .where(:post_votes => { :post_id => id })
        .order("post_votes.updated_at DESC")
        .group_by(&:vote_score)
  end

  def favorited_by
    voted_by[3] || []
  end

  def author
    (user || AnonymousUser.new).name
  end

  def delete_from_database
    delete_file
    execute_sql("DELETE FROM posts WHERE id = ?", id)
  end

  def active_notes
    notes.select(&:is_active?)
  end

  STATUSES.each do |x|
    define_method("is_#{x}?") do
      return status == x
    end
  end

  def can_be_seen_by?(user, options = {})
    if !options[:show_deleted] && status == "deleted"
      return false
    end
    CONFIG["can_see_post"].call(user, self)
  end

  def self.new_deleted?(user)
    conds = []
    conds += ["creator_id <> %d" % [user.id]] unless user.is_anonymous?

    newest_topic = ForumPost.where(conds).order(:id => :desc).select(:created_at).take
    return false if newest_topic.nil?
    newest_topic.created_at > user.last_forum_topic_read_at
  end

  def normalized_source
    if source =~ /(pixiv\.net|pximg\.net)\/img/
      img_id = source[/(\d+)(_s|_m|(_big)?_p\d+)?\.\w+(\?\d+)?\z/, 1]
      "http://www.pixiv.net/member_illust.php?mode=medium&illust_id=#{img_id}"
    elsif source =~ /\Ahttps?:\/\//i
      source
    else
      "http://#{source}"
    end
  end

  def service
    CONFIG["local_image_service"]
  end

  def service_icon
    "/favicon.ico"
  end

  def self.refresh_tags_array
    max_id = maximum(:id)

    (0..((max_id/1000).floor)).each do |i|
      start_id = i * 1000 + 1
      end_id = (i + 1) * 1000

      Rails.logger.info "Updating tags array for post #{start_id}..#{end_id} of #{max_id}"
      where('id BETWEEN ? AND ?', start_id, end_id).update_all "tags_array = string_to_array(cached_tags, ' ')"
    end
  end
end

app/models/post/cache_methods.rb
module Post::CacheMethods
  def self.included(m)
    m.after_save :expire_cache
    m.after_destroy :expire_cache
  end

  def expire_cache
    # FIXME: this removes too many caches.
    # Reference: https://github.com/moebooru/moebooru/commit/896dbff
    Moebooru::CacheHelper.increment_version
  end
end

app/models/post/change_sequence_methods.rb
module Post::ChangeSequenceMethods
  attr_accessor :increment_change_seq

  def self.included(m)
    m.before_create :touch_change_seq!
    m.after_save :update_change_seq
  end

  def touch_change_seq!
    self.increment_change_seq = true
  end

  def update_change_seq
    return if increment_change_seq.nil?
    execute_sql("UPDATE posts SET change_seq = nextval('post_change_seq') WHERE id = ?", id)
    self.change_seq = select_value_sql("SELECT change_seq FROM posts WHERE id = ?", id)
  end
end

app/models/post/comment_methods.rb
module Post::CommentMethods
  def self.included(m)
    m.has_many :comments, lambda { order "id" }
  end

  def recent_comments
    # reverse_order to fetch last 6 comments
    # reversed in the last to return from lowest id
    comments.reverse_order.limit(6).reverse
  end
end

app/models/post/image_store_methods.rb
module Post::ImageStoreMethods
  def self.included(m)
    case CONFIG["image_store"]
    when :local_flat then m.__send__(:include, Post::ImageStore::LocalFlat)
    when :local_hierarchy then m.__send__(:include, Post::ImageStore::LocalHierarchy)
    when :remote_hierarchy then m.__send__(:include, Post::ImageStore::RemoteHierarchy)
    else m.__send__(:include, Post::ImageStore::Local2)
    end
  end

  private

  def url_encode(*args)
    ERB::Util.url_encode *args
  end
end

app/views/post/show_partials/_comments.html.erb
<div id="comments" style="margin-top: 1em; max-width: 800px; width: 100%;">
  <%= render :partial => "comment/comments", :locals => {:comments => @post.comments, :post_id => @post.id, :hide => false} %>
</div>

app/views/post/show_partials/_edit.html.erb
<div id="edit" style="display: none;">
  <%= form_tag({:controller => "post", :action => "update", :id => @post.id}, :id => "edit-form", :level => :member) do %>
    <%= hidden_field_tag "post[old_tags]", @post.cached_tags %>
    <table class="form">
      <tfoot>
        <tr>
          <td colspan="2"><%= submit_tag t('.save'), :tabindex => 11, :accesskey => "s" %></td>
        </tr>
      </tfoot>
      <tbody>
        <tr>
          <th width="15%">
            <label class="block" for="post_rating_questionable"><%= t('.rating') %></label>
            <% unless @current_user.is_privileged_or_higher? %>
              <p><%= t('.rating_info_html', :more => link_to(t('.help'), help_path("ratings"), :target => "_blank")) %></p>
            <% end %>
          </th>
          <td width="85%">
            <% if @post.is_rating_locked? %>
              <%= t('.rating_locked_info') %>
            <% else %>
              <%= radio_button_tag "post[rating]", "Explicit", @post.rating == "e", :id => "post_rating_explicit", :tabindex => 1 %>
              <label for="post_rating_explicit"><%= t('ratings.e') %></label>
              <%= radio_button_tag "post[rating]", "Questionable", @post.rating == "q", :id => "post_rating_questionable", :tabindex => 2 %>
              <label for="post_rating_questionable"><%= t('ratings.q') %></label>
              <%= radio_button_tag "post[rating]", "Safe", @post.rating == "s", :id => "post_rating_safe", :tabindex => 3 %>
              <label for="post_rating_safe"><%= t('ratings.s') %></label>
            <% end %>
          </td>
        </tr>
        <tr>
          <th><label><%= t('.parent') %></label></th>
          <td><%= text_field "post", "parent_id", :size => 10, :tabindex => 4 %></td>
        </tr>
          <tr>
            <th><label class="block" for="post_is_shown_in_index"><%= t('.shown_in_index') %></label></th>
            <td><%= check_box "post", "is_shown_in_index", :tabindex => 7 %></td>
          </tr>
        <% if @current_user.is_privileged_or_higher? %>
          <tr>
            <th><label class="block" for="post_is_note_locked"><%= t('.note_locked') %></label></th>
            <td><%= check_box "post", "is_note_locked", :tabindex => 7 %></td>
          </tr>
          <tr>
            <th><label class="block" for="post_is_rating_locked"><%= t('.rating_locked') %></label></th>
            <td><%= check_box "post", "is_rating_locked", :tabindex => 8 %></td>
          </tr>
        <% end %>
        <tr>
          <th><label class="block" for="post_source"><%= t('.source') %></label></th>
          <td><%= text_field "post", "source", :size => 40, :tabindex => 9 %></td>
        </tr>
          <tr>
            <th>
              <label class="block" for="post_tags"><%= t('.tags') %></label>
              <% unless @current_user.is_privileged_or_higher? %>
                <p><%= t('.tags_info_html', :more => link_to(t('.help'), help_path('tags'), :target => '_blank')) %></p>
              <% end %>
            </th>
            <td>
              <%= text_area "post", "tags", :readonly => !@post.can_be_seen_by?(@current_user), :size => "50x4", :value => tag_string(@tags[:include]), :tabindex => 10 %>
            <% if @post.can_be_seen_by?(@current_user) %>
              <%= link_to t(".related.tags"), "#", :data => { :toggle => "related-tags", :type => "all" } %> |
              <%= link_to t(".related.artists"), "#", :data => { :toggle => "related-tags", :type => "artist" } %> |
              <%= link_to t(".related.characters"), "#", :data => { :toggle => "related-tags", :type => "char" } %> |
              <%= link_to t(".related.copyrights"), "#", :data => { :toggle => "related-tags", :type => "copyright" } %> |
              <%= link_to t("post.upload.form.find_related.circles"), "#", :data => { :toggle => "related-tags", :type => "circle" } %>
              <% if CONFIG["enable_artists"] %>
                | <%= link_to t(".find_artists"), "#", :data => { :toggle => "related-tags", :type => "artist-url" } %>
              <% end %>
            <% end %>
            </td>
          </tr>
      </tbody>
    </table>
    <div>
      <h5><%= t('.related.tags').titleize %></h5>
      <div style="margin-bottom: 1em;" id="related"><em><%= t('.related.none') %></em></div>
    </div>
  <% end %>
</div>

app/views/post/show_partials/_history_panel.html.erb
<div>
  <h5><%= t('.title') %></h5>
  <ul>
    <li><%= link_to t('.tags'), :controller => "history", :action => "index", :search => "post:#{@post.id}" %></li>
    <li><%= link_to t('.notes'), :controller => "note", :action => "history", :post_id => @post.id %></li>
  </ul>
</div>

app/views/post/show_partials/_image.html.erb
<% if !@post.is_deleted? %>
  <div>
    <% if !@post.can_be_seen_by?(@current_user) %>
      <p><%= t('.denied') %></p>
    <% elsif @post.image? %>
      <div id="note-container">
        <% @post.active_notes.each do |note| %>
          <div class="note-box" style="width: <%= note.width %>px; height: <%= note.height %>px; top: <%= note.y %>px; left: <%= note.x %>px;" id="note-box-<%= note.id %>">
            <div class="note-corner" id="note-corner-<%= note.id %>"></div>
          </div>
           <div class="note-body" id="note-body-<%= note.id %>" title="Click to edit"><%= sanitize note.formatted_body %></div>
        <% end %>
      </div>
      <% file_sample = @post.get_file_sample(@current_user) %>
      <%= image_tag(file_sample[:url],
                    :alt => @post.cached_tags,
                    :id => 'image',
                    :class => "image",
                    :width => file_sample[:width],
                    :height => file_sample[:height],
                    :large_width => @post.get_file_jpeg(@current_user)[:width],
                    :large_height => @post.get_file_jpeg(@current_user)[:height]) %>
    <% elsif @post.flash? %>
      <object width="<%= @post.width %>" height="<%= @post.height %>">
        <param name="movie" value="<%= @post.file_url %>">
        <embed src="<%= @post.file_url %>" width="<%= @post.width %>" height="<%= @post.height %>" allowScriptAccess="never"></embed>
      </object>

      <p><%= link_to t('.save_flash'), @post.file_url %></p>
    <% else %>
      <h2><a href="<%= @post.file_url %>"><%= t('.download._') %></a></h2>
      <p><%= t('.download.info') %></p>
    <% end %>
  </div>
  <div style="margin-bottom: 1em;">
    <p id="note-count"></p>
    <script type="text/javascript">
      Note.post_id = <%= @post.id %>

      <% @post.active_notes.each do |note| %>
        Note.all.push(new Note(<%= note.id %>, false, '<%= h note.body.to_escaped_js %>'))
      <% end %>

      Note.updateNoteCount()
      Note.show()

      //new WindowDragElement($("image"));
      Moebooru.dragElement(jQuery('.image'));

      $("image").observe("click", function(e) { if(!e.stopped) Note.toggle(); }.bindAsEventListener());
    </script>
  </div>
<% end %>

app/views/post/show_partials/_image_footer.html.erb
<div>
  <h4>
    <%= link_to t(".edit"), "#", :class => "js-posts-show-edit-tab" %> | <%= link_to t(".respond"), "#", :class => "js-posts-show-comments-tab" %>
  </h4>
</div>

app/views/post/show_partials/_pool.html.erb
<div class="status-notice" id="pool<%= pool.id %>">
  <div style="display: inline;">
    <p>
      <% if pool_post.prev_post_id %>
        <%= link_to t('.previous'), :action => "show", :id => pool_post.prev_post_id, :pool_id => pool_post.pool_id %>
      <% end %>
      <% if pool_post.next_post_id %>
        <%= link_to t('.next'), :action => "show", :id => pool_post.next_post_id, :pool_id => pool_post.pool_id %>
      <% end %>
      <%= t('.info_html', :sequence => content_tag(:span, pool_post.pretty_sequence, :id => "pool-seq-#{pool_post.pool_id}"), :pool => link_to(pool.pretty_name, :controller => "pool", :action => "show", :id => pool.id)) %>
      <% pooled_post_id = @post.id %>

    <% if @current_user.can_change?(pool_post, :active) %>
      <span class="advanced-editing">
        (<%= link_to_function t('.remove._'), "if(confirm('#{t('.remove.confirm', :current_pool => escape_javascript(pool.pretty_name))}')) Pool.remove_post(#{@post.id}, #{pool.id})"
        -%>, <%= link_to_function t('.change'), "Pool.change_sequence(#{@post.id}, #{pool_post.pool_id}, #{pool_post.sequence.to_json})"
        -%><%- if not @post.parent_id.nil?
        -%>, <%= link_to_function t('.transfer._'), "if(confirm('#{t('.transfer.confirm', :current_pool => escape_javascript(pool.pretty_name))}')) Pool.transfer_post(#{@post.id}, #{@post.parent_id}, #{pool.id}, #{pool_post.sequence.to_json})"
        -%><%- end -%>)
      </span>
    <%- end %>
    </p>
  </div>
</div>